### PR TITLE
String Export - Cobalt

### PR DESCRIPTION
**Pull request by pocmo**
Those are the new strings for the Cobalt release.

String freeze was supposed to be Aug 24, 2017 - but we delayed it to due to the changed Burgundy deadlines.

https://wiki.mozilla.org/Mobile/Focus/Android/Train_Schedule

### CODE REVIEW

**Review by flodolo — APPROVED** [review]

**Comment by mathjazz** [comment]
Looks like cak, mix, trs and zam were left out.

**Comment by mathjazz** [comment]
Note: Pontoon will show the new strings to those locales, too.

Still, it might be a good idea to check out the update script.

**Comment by flodolo** [comment]
Good point (looks like the issue was there also in previous exports). 

Those 3 languages can't be enabled in Focus at the moment, not sure if it's the same underlying issue with the conversion tool (likely).

**Comment by pocmo** [comment]
Yeah, our tool currently can't import/export those locales:
https://github.com/mozilla-mobile/focus-android/issues/1148

We want to fix this in the next sprint.

**Pull request merged**
