### PR TITLE
Added basque translation

### PR DESCRIPTION
**Pull request by dgarciabad**

### CODE REVIEW

**Comment by flodolo** [comment]
CC @delphine and @julen 
Thanks for your contribution. 

For the future, I would really suggest to get in touch with the existing team before starting, to agree on the best process, style, etc ;-)

https://wiki.mozilla.org/L10n:Teams:eu

**Comment by julen** [comment]
Hi, thanks for bringing this to my attention @flodolo and for the time taken @dgarciabad.

I cannot accept this contribution as-is due to multiple reasons:
1. We work on mozilla.locamotion.org as it allows us to reuse previous translations easily, and pulling translations from other sources doesn't help in this regards (albeit having Transvision)
2. Having Focus for iOS already localized allows us to easily and consistently reuse that work for Android.
3. Focus was already requested to be added to MLO to @Delphine, but apparently there is some technical problem on Mozilla's side.

All of this was already transmitted over the weekend [in a message posted in our Librezale mailing list](https://librezale.eus/pipermail/librezale/2017-July/013390.html). We also reiterated that the first step before doing any work is to contact existing people in charge of projects.

I suggest we wait until the Focus for Android project is ready in MLO and then anyone can join in the localizing efforts. Having the translation memory results will also greatly help keep the style and terminology consistent across projects.

Last but not least, @Delphine and @flodolo, would you be open to add a note in the repo's README file mentioning where the locale directory contents are coming from? That would prevent misleading people with respect to making contributions.

**Comment by flodolo** [comment]
> Last but not least, @Delphine and @flodolo, would you be open to add a note in the repo's README file mentioning where the locale directory contents are coming from? That would prevent misleading people with respect to making contributions.

We definitely need to do that, on all our repositories. I was hoping to have a document to point to, but we might need it earlier than that.

**Comment by pocmo** [comment]
> Last but not least, @Delphine and @flodolo, would you be open to add a note in the repo's README file mentioning where the locale directory contents are coming from? That would prevent misleading people with respect to making contributions.

It would be helpful to add a short paragraph about how to translate Focus to the [focus-android](https://github.com/mozilla-mobile/focus-android) repository too. Every now and then we get a pull request updating (or adding) Android string files directly. I usually send those folks here or to Pontoon. But as I see here this might not be helpful either.

**Comment by Delphine** [comment]
@pocmo : Absolutely. I'll to this once we have that text all ready to go :)

**Comment by flodolo** [comment]
I've edited the README a bit.
https://github.com/mozilla-l10n/focus-android-l10n/commit/f04e7a5b052468d864f4ddc60adfb62f31e2e7b5

Let's close this one, and see if that's enough.

**Pull request closed without merging**
