### PR TITLE
Export Folly strings

### PR DESCRIPTION
**Pull request by liuche**
There is a single string to be added for Folly: https://github.com/mozilla-l10n/focus-android-l10n/commit/fe1e93859fc3026078bf44dc5684f262fa5ec089

However, there are a lot of changes in these files (possibly because we're using some new scripts) so here's context:

- There are additional changes to this PR has a bunch of whitespace changes that are strictly line-wrap changes, and don't change the string names or the strings themselves. I believe this might be a known bug in android2po: https://github.com/miracle2k/android2po/issues/49 but I'm not sure why these are surfacing here.
- In the header/metadata of each .po file, the "X-Generator: Pontoon" line is missing, investigating this.

### CODE REVIEW

**Comment by flodolo** [comment]
> There are additional changes to this PR has a bunch of whitespace changes that are strictly line-wrap changes, and don't change the string names or the strings themselves. I believe this might be a known bug in android2po: miracle2k/android2po#49 but I'm not sure why these are surfacing here.
> In the header/metadata of each .po file, the "X-Generator: Pontoon" line is missing, investigating this.

Both are expected, you should look at the [changes to templates](https://github.com/mozilla-l10n/focus-android-l10n/pull/21/commits/fe1e93859fc3026078bf44dc5684f262fa5ec089) for a better reference.

The first is due to Pontoon and the script to use a different serializer when writing to the file, the second is just meta data related to the editor (e.g. it would change if you touch the file with POEdit).

Check the [previous PR](https://github.com/mozilla-l10n/focus-android-l10n/pull/19) for reference.

Leaving the review to Delphine (I see the CODEOWNER trick worked), you'll need to discuss timing of these PRs ;-)

**Review by Delphine — APPROVED** [review]
Since this is just one string I'll still get it in for this time, although we missed the schedule. thanks

**Comment by Delphine** [comment]
Hmm not sure why there are conflicts between ast and el files. Looking into this now.

**Comment by Delphine** [comment]
@liuche: Please next time when I say I'm going offline and can't check a PR of strings for 2 days, don't go ahead and do a pull request anyways. Localizers went in and translated the strings in the meantime, which resulted in a lot of conflicts. I specifically said on Slack I wasn't going to be around, and that we were skipping this. Let's try to sync up better next time. Thanks

**Comment by liuche** [comment]
Oh, I'm sorry about the conflicts and the extra work this caused, @Delphine - I assumed that PRs aren't intended for translation until they've merged into the main repository (in my experience this is how other projects work, because anyone on Github can make a PR). Is there somewhere I can read more about the process (or could you let me know if there are other things I should watch out for)? I'll also make a PR to this repo's README if you want to make this clearer to people that PRs will be seen and acted upon by translators, and I'll update the documentation on our side too to make that clear.

**Comment by flodolo** [comment]
Translators don't do anything on PRs.

As you noticed, when you export you reformat all the files. In the meantime, translators go in and translate old missing strings, creating merge conflicts.

As for documentation, the process was created by Sebastian, we don't have any since it's on the development side of things.

**Comment by Delphine** [comment]
@liuche: thanks for your message. No harm done! we'll just have to make sure we sync up better next times. cheers

**Comment by liuche** [comment]
Thanks for the clarification! That's my bad, I forgot that these files are updated all the time, so it makes sense that a PR can get stale really quickly. I made a PR to your README just so other people won't make that mistake again, and also updated the instructions on our end to be more explicit too.

In the future, if there are conflicts, please reach out to the person making the PR because I think it should be up to them to fix conflicts! Sorry again for making you have to resolve all of them, I can imagine it was a huge pain because there are so many files x_x

**Pull request merged**
