### PR TITLE
6.0 strings

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Review by Delphine — APPROVED** [review]
LGTM, thanks

**Comment by Delphine** [comment]
(side-note: it's usually better to wait for me to be online to make a string export, because if other people translate in the meantime, there will be conflicts with the base branch. Thankfully it's not the case this time ;) )

**Comment by boek** [comment]
@Delphine Ah! Good to know! I'll be sure to wait next time.

**Comment by Delphine** [comment]
Side-note: I will catch-up with @npark-mozilla next week to get updated screenshots for the 6.0 strings.

**Pull request merged**
